# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20160501_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Indicates if the deal conditions still apply', verbose_name='Expired'),
        ),
    ]
