# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='deal_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Optional field. The deal expires at this date', null=True, verbose_name='Expires at'),
        ),
    ]
